[package]
name = "easy_maa"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy="0.15"
log = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
reqwest = "0.12"
serde_urlencoded = "0.7"
regex = "1.12"
tokio = { version = "1", features = ["full"] }